# Set the base image to Nginx
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER Emiliano Molina <emiliano.g.molina@gmail.com>

# Create the log directory
RUN mkdir -p /var/log/webapp

# Create the log volume
VOLUME /var/log/webapp

CMD ["/bin/sh"]
